# Generated by Django 4.2 on 2023-04-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attackscategory',
            name='createDate',
        ),
        migrations.CreateModel(
            name='Attacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attackName', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(verbose_name='date created')),
                ('attackCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attacks.attackscategory')),
            ],
        ),
    ]
