# Generated by Django 4.2 on 2023-04-08 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0002_remove_attackscategory_createdate_attacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacks',
            name='attackDesc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attacks',
            name='drsLevel',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
    ]
