# Generated by Django 4.2 on 2023-04-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0003_attacks_attackdesc_attacks_drslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacks',
            name='attackDesc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='attackscategory',
            name='categoryDesc',
            field=models.CharField(max_length=300),
        ),
    ]
