# Generated by Django 4.2 on 2023-04-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0004_alter_attacks_attackdesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacks',
            name='attackDesc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attackscategory',
            name='categoryDesc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='attackscategory',
            name='categoryName',
            field=models.CharField(max_length=100),
        ),
    ]
