# Generated by Django 4.2 on 2023-06-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0007_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mail',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
