# Generated by Django 4.2 on 2023-06-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0008_users_mail_users_name_users_surname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
